#!/bin/bash --login
#PBS -N carpet
#PBS -A e283-lianhua
#PBS -l select=1
#PBS -l walltime=00:20:00
#PBS -m abe
#PBS -M zhulianhua121@gmail.com

# Switch to current working directory
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=12
export OMP_SCHEDULE="dynamic"
export PATH=$PATH:/work/e283/e283/lhzhu/mpi_dvm/build
# Run the serial program
date
aprun -n 1 -N 1 -S 1 -d 12 dvm.x > log
date
